export { loginUser } from './authRoutes'
export { getCalendar, uploadFileTypeModeus } from './calendarRoutes'
export { createEvent } from './eventsRoutes'
export { createProject, deleteProject, editProject, getAllProjects } from './projectRoutes'
export { createTask, deleteTask, editTask, getTask } from './taskRoutes'
export {} from './userRoutes'
